import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css"; // Import the globals.css";
import NextTopLoader from 'nextjs-toploader';
import Navbar from "../components/Dashboard/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Dashboard - SkillMatch Network",
    description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
    return (
        <html lang="en">
            <head>
                {/* Metadata */}
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Navbar />

                <NextTopLoader
                    color="#0d6efd"
                    initialPosition={0.08}
                    crawlSpeed={200}
                    height={3}
                    crawl={true}
                    showSpinner={true}
                    easing="ease"
                    speed={200}
                    shadow="0 0 10px #0d6efd,0 0 5px #0d6efd"
                    template='<div class="bar" role="bar"><div class="peg"></div></div>
          <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
                    zIndex={1600}
                    showAtBottom={false}
                />
                <div className="container mt-5">
                    <div className="row">
                        <div className="col-md-3">
                            <div className="list-group">
                                <a href="#" className="list-group-item list-group-item-action active">
                                    Dashboard
                                </a>
                                <a href="#" className="list-group-item list-group-item-action">
                                    My Skills
                                </a>
                                <a href="#" className="list-group-item list-group-item-action">
                                    Job Matches
                                </a>
                                <a href="#" className="list-group-item list-group-item-action">
                                    Messages
                                </a>
                            </div>
                        </div>
                        <div className="col-md-9">
                            {children}
                        </div>
                    </div>
                </div>

            </body>
        </html>
    );
}
